### ISSUE TITLE
Add Inference example Sampler

### ISSUE THREAD

**Issue by ClementCaporal** [TheJacksonLaboratory/zarrdataset#3]
Hello,

Thank you for your work!

## use case
 
I would like to use this library to load my larger-than-memory zarr dataset for inference.
I _think_ it is not currently possible with the current Sampler classes.

What would be your approach for this task?

I will try in the following to follow the semantic I understood from the code base:
https://github.com/TheJacksonLaboratory/zarrdataset/blob/fb57026a1ed7436603d66b440ab4f9ebfee377f9/zarrdataset/_samplers.py#L264-L265

## Proposed solution

From my understanding a new Sampler Class would be needed:
1. Define an overlap size (eg, for a patch of (64, 128,128), overlap of (4, 16, 16))
2. Chunk should be computed with this overlap between them.  (Replacing [ `_compute_grid`](https://github.com/TheJacksonLaboratory/zarrdataset/blob/fb57026a1ed7436603d66b440ab4f9ebfee377f9/zarrdataset/_samplers.py#L107))
3. Patches inside the chunk should also be computed with an overlap replacing [`_compute_valid_toplefts`](https://github.com/TheJacksonLaboratory/zarrdataset/blob/fb57026a1ed7436603d66b440ab4f9ebfee377f9/zarrdataset/_samplers.py#L232)

Do you think this would allow an efficient patch zarr loading with multiple workers?

## Problems

I have one main issue with this strategy:
Overlap in chunk might create issues concerning this comment (what is the user choose an overlap that is not equal to the zarr chunk sizes). 
https://github.com/TheJacksonLaboratory/zarrdataset/blob/fb57026a1ed7436603d66b440ab4f9ebfee377f9/zarrdataset/_samplers.py#L267-L268

If this overlap-chunk loading is a valid issue:
Can we get rid of the "chunk" logic and distribute the worker over the  "patches" directly.

---

Thank you,

Clément

**Comment by fercer** [comment]
Hi @ClementCaporal, thanks for using zarrdataset!

Adding a sampler to obtain overlapped patches would indeed make zarrdataset useful for inference on large zarr datasets.
I'll be working on that addition since I might be using that functionality as well.

The chunk logic makes sense when sampling patches at random locations. Loading a full zarr chunk only to extract a single patch inside it is not efficient. That is the case when this operation is repeated multiple times, e.g., training with minibatches.

For this case I might start with implementing the sampler. So, a chunk can be loaded and cached, and all the overlapping patches within that chunk can be extracted. When all the patches have been exhausted, repeat with the next chunk.

I'll keep the chunk logic for now also because a list of patches is expected to be orders of magnitude greater than the number of chunks. So, manipulating lists of that size could be prohibitive when scattering the patches across multiple workers.

**Comment by ClementCaporal** [comment]
Thank you for your answer @fercer!

Keeping the chunk logic seems fine to me too.
Considering you find all the overlap patches inside the chunk:
- From what i understand for now: zarr-chunk == pytorch-worker-chunk (aka the size of a chunk in the zarr structure is used for the chunk given to the workers)
- How will you create overlap between the chunks? Should the sampler load several neighbors zarr-chunks to create one bigger chached pytorch-worker-chunk?
- If this pytorch worker-chunk exist, keep the needed overlap with the next pytorch-worker-chunk?

I would be happy to help/ peer-coding to see how you would test solutions and implement.

To give a bit of context for my application/motivation:
I have a 1.57To zarr with a shape  (3, 1799, 14848, 15360) saved as chunk of (1, 3, 64, 512, 512) that I would like to load in my pytorch model that take input (1, 3, 17, 128, 128).

**Comment by fercer** [comment]
Hey @ClementCaporal, I made a slight modification to the base `zarrdataset.PatchSampler` class to use `patch_size` as base shape to generate and distribute the chunks to the different workers.
The modification is in PR #4. Basically this changes pytorch-worker-chunks to be multiple of `patch_size`.

This removes the dependency to zarr-chunks and allows workers to load neighbor zarr-chunks only when necessary.
In the example you gave, at most three chunks will be loaded (for Z axis) when a patch is between two zarr-chunks. The other two spatial axes divide the zarr-chunks exactly, so no extra neighbor zarr-chunks would be loaded for them.

There shouldn't be impact to the pytorch workers since each of them have their own handler to open the zarr file.
And it doesn't matter that pytorch-workers-chunks overlap since this is a read-only operation.

It would be great if you could test the functionality. The patch sampler would be the same `zarrdataset.PatchSampler`.
Let me know your thoughts!

**Comment by ClementCaporal** [comment]
Hello thank you very much! Sorry for the delay
I wanted to test this functionality. It works fine speed-wise!
I tried to implement a complete PatchSampler with overlap between the patches (to remove the edge effect from my model prediction).

I ran into new issue that is (I think) useful to discuss before closing this issue: #5 

Thank you again,

Clément

**Comment by fercer** [comment]
In PR #4 new arguments have been added to the `PatchSampler` class to retrieve "padded" patches.
Also, `ImageBase` has been updated to handle those padded patches with actual pixels from neighboring chunks.

Set `allow_incomplete_patches=True` and pass the amount of padding in `pad` when creating the `PatchSampler` to use this sampler for inference.
